# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(747, 591)
        Dialog.setStyleSheet("background-color: rgb(106, 159, 159);")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(230, 360, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.btn_Search_For_CarData_By_CarNo = QtWidgets.QPushButton(Dialog)
        self.btn_Search_For_CarData_By_CarNo.setGeometry(QtCore.QRect(30, 70, 101, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_Search_For_CarData_By_CarNo.setFont(font)
        self.btn_Search_For_CarData_By_CarNo.setObjectName("btn_Search_For_CarData_By_CarNo")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(-10, 130, 711, 451))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.tabWidget.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.txt_Car_Car_Number = QtWidgets.QLineEdit(self.tab)
        self.txt_Car_Car_Number.setGeometry(QtCore.QRect(370, 50, 251, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt_Car_Car_Number.setFont(font)
        self.txt_Car_Car_Number.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.txt_Car_Car_Number.setObjectName("txt_Car_Car_Number")
        self.txt_Car_Shaceh_Number = QtWidgets.QLineEdit(self.tab)
        self.txt_Car_Shaceh_Number.setGeometry(QtCore.QRect(373, 211, 251, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt_Car_Shaceh_Number.setFont(font)
        self.txt_Car_Shaceh_Number.setObjectName("txt_Car_Shaceh_Number")
        self.txt_Car_Motor_Number = QtWidgets.QLineEdit(self.tab)
        self.txt_Car_Motor_Number.setGeometry(QtCore.QRect(373, 251, 251, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt_Car_Motor_Number.setFont(font)
        self.txt_Car_Motor_Number.setObjectName("txt_Car_Motor_Number")
        self.txt_Car_Owner_Company = QtWidgets.QLineEdit(self.tab)
        self.txt_Car_Owner_Company.setGeometry(QtCore.QRect(373, 89, 251, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt_Car_Owner_Company.setFont(font)
        self.txt_Car_Owner_Company.setObjectName("txt_Car_Owner_Company")
        self.txt_Car_Branch = QtWidgets.QLineEdit(self.tab)
        self.txt_Car_Branch.setGeometry(QtCore.QRect(373, 129, 251, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt_Car_Branch.setFont(font)
        self.txt_Car_Branch.setObjectName("txt_Car_Branch")
        self.txt_Car_Car_Load = QtWidgets.QLineEdit(self.tab)
        self.txt_Car_Car_Load.setGeometry(QtCore.QRect(52, 129, 251, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt_Car_Car_Load.setFont(font)
        self.txt_Car_Car_Load.setObjectName("txt_Car_Car_Load")
        self.txt_Car_Car_Wieght = QtWidgets.QLineEdit(self.tab)
        self.txt_Car_Car_Wieght.setGeometry(QtCore.QRect(51, 169, 251, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt_Car_Car_Wieght.setFont(font)
        self.txt_Car_Car_Wieght.setObjectName("txt_Car_Car_Wieght")
        self.txt_Car_Car_Shape = QtWidgets.QLineEdit(self.tab)
        self.txt_Car_Car_Shape.setGeometry(QtCore.QRect(51, 209, 251, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt_Car_Car_Shape.setFont(font)
        self.txt_Car_Car_Shape.setObjectName("txt_Car_Car_Shape")
        self.txt_Car_Car_Type = QtWidgets.QLineEdit(self.tab)
        self.txt_Car_Car_Type.setGeometry(QtCore.QRect(53, 49, 251, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt_Car_Car_Type.setFont(font)
        self.txt_Car_Car_Type.setObjectName("txt_Car_Car_Type")
        self.txt_Car_Car_Model = QtWidgets.QLineEdit(self.tab)
        self.txt_Car_Car_Model.setGeometry(QtCore.QRect(53, 89, 251, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt_Car_Car_Model.setFont(font)
        self.txt_Car_Car_Model.setObjectName("txt_Car_Car_Model")
        self.txt_Car_Car_Color = QtWidgets.QLineEdit(self.tab)
        self.txt_Car_Car_Color.setGeometry(QtCore.QRect(50, 249, 251, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt_Car_Car_Color.setFont(font)
        self.txt_Car_Car_Color.setObjectName("txt_Car_Car_Color")
        self.btn_Add_Car_Info = QtWidgets.QPushButton(self.tab)
        self.btn_Add_Car_Info.setGeometry(QtCore.QRect(503, 369, 121, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_Add_Car_Info.setFont(font)
        self.btn_Add_Car_Info.setObjectName("btn_Add_Car_Info")
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setGeometry(QtCore.QRect(325, 39, 16, 301))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.btn_Update_Car_Info = QtWidgets.QPushButton(self.tab)
        self.btn_Update_Car_Info.setGeometry(QtCore.QRect(373, 369, 121, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_Update_Car_Info.setFont(font)
        self.btn_Update_Car_Info.setObjectName("btn_Update_Car_Info")
        self.btn_Delete_Car_Info = QtWidgets.QPushButton(self.tab)
        self.btn_Delete_Car_Info.setGeometry(QtCore.QRect(113, 369, 121, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_Delete_Car_Info.setFont(font)
        self.btn_Delete_Car_Info.setObjectName("btn_Delete_Car_Info")
        self.cbo_Car_Service_Mode = QtWidgets.QComboBox(self.tab)
        self.cbo_Car_Service_Mode.setGeometry(QtCore.QRect(370, 170, 251, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cbo_Car_Service_Mode.setFont(font)
        self.cbo_Car_Service_Mode.setObjectName("cbo_Car_Service_Mode")
        self.cbo_Car_Service_Mode.addItem("")
        self.cbo_Car_Service_Mode.addItem("")
        self.cbo_Car_Service_Mode.addItem("")
        self.cbo_Car_Fuel_Type = QtWidgets.QComboBox(self.tab)
        self.cbo_Car_Fuel_Type.setGeometry(QtCore.QRect(370, 292, 251, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cbo_Car_Fuel_Type.setFont(font)
        self.cbo_Car_Fuel_Type.setObjectName("cbo_Car_Fuel_Type")
        self.cbo_Car_Fuel_Type.addItem("")
        self.cbo_Car_Fuel_Type.addItem("")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.liter_number = QtWidgets.QLineEdit(self.tab_2)
        self.liter_number.setGeometry(QtCore.QRect(317, 83, 251, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.liter_number.setFont(font)
        self.liter_number.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.liter_number.setObjectName("liter_number")
        self.liter_price = QtWidgets.QLineEdit(self.tab_2)
        self.liter_price.setGeometry(QtCore.QRect(315, 203, 251, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.liter_price.setFont(font)
        self.liter_price.setObjectName("liter_price")
        self.tips = QtWidgets.QLineEdit(self.tab_2)
        self.tips.setGeometry(QtCore.QRect(315, 163, 251, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tips.setFont(font)
        self.tips.setObjectName("tips")
        self.meter_reading = QtWidgets.QLineEdit(self.tab_2)
        self.meter_reading.setGeometry(QtCore.QRect(315, 123, 251, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.meter_reading.setFont(font)
        self.meter_reading.setObjectName("meter_reading")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(135, 106, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lcdtotal_fuel = QtWidgets.QLCDNumber(self.tab_2)
        self.lcdtotal_fuel.setGeometry(QtCore.QRect(130, 144, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lcdtotal_fuel.setFont(font)
        self.lcdtotal_fuel.setObjectName("lcdtotal_fuel")
        self.btn_Update_Fuel_Info = QtWidgets.QPushButton(self.tab_2)
        self.btn_Update_Fuel_Info.setGeometry(QtCore.QRect(315, 263, 121, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_Update_Fuel_Info.setFont(font)
        self.btn_Update_Fuel_Info.setObjectName("btn_Update_Fuel_Info")
        self.btn_Add_Fuel_Info = QtWidgets.QPushButton(self.tab_2)
        self.btn_Add_Fuel_Info.setGeometry(QtCore.QRect(445, 263, 121, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_Add_Fuel_Info.setFont(font)
        self.btn_Add_Fuel_Info.setObjectName("btn_Add_Fuel_Info")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.txt_afsha = QtWidgets.QLineEdit(self.tab_3)
        self.txt_afsha.setGeometry(QtCore.QRect(392, 221, 251, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt_afsha.setFont(font)
        self.txt_afsha.setObjectName("txt_afsha")
        self.txt_engine_amra = QtWidgets.QLineEdit(self.tab_3)
        self.txt_engine_amra.setGeometry(QtCore.QRect(394, 60, 251, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt_engine_amra.setFont(font)
        self.txt_engine_amra.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.txt_engine_amra.setObjectName("txt_engine_amra")
        self.txt_periodic_maintenance = QtWidgets.QLineEdit(self.tab_3)
        self.txt_periodic_maintenance.setGeometry(QtCore.QRect(390, 260, 251, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt_periodic_maintenance.setFont(font)
        self.txt_periodic_maintenance.setObjectName("txt_periodic_maintenance")
        self.txt_samkara = QtWidgets.QLineEdit(self.tab_3)
        self.txt_samkara.setGeometry(QtCore.QRect(392, 181, 251, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt_samkara.setFont(font)
        self.txt_samkara.setObjectName("txt_samkara")
        self.txt_electricity = QtWidgets.QLineEdit(self.tab_3)
        self.txt_electricity.setGeometry(QtCore.QRect(392, 140, 251, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt_electricity.setFont(font)
        self.txt_electricity.setObjectName("txt_electricity")
        self.txt_cooling = QtWidgets.QLineEdit(self.tab_3)
        self.txt_cooling.setGeometry(QtCore.QRect(73, 59, 251, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt_cooling.setFont(font)
        self.txt_cooling.setObjectName("txt_cooling")
        self.txt_mechanics = QtWidgets.QLineEdit(self.tab_3)
        self.txt_mechanics.setGeometry(QtCore.QRect(392, 100, 251, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt_mechanics.setFont(font)
        self.txt_mechanics.setObjectName("txt_mechanics")
        self.txt_glass = QtWidgets.QLineEdit(self.tab_3)
        self.txt_glass.setGeometry(QtCore.QRect(72, 99, 251, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt_glass.setFont(font)
        self.txt_glass.setObjectName("txt_glass")
        self.txt_notes = QtWidgets.QPlainTextEdit(self.tab_3)
        self.txt_notes.setGeometry(QtCore.QRect(72, 140, 251, 151))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt_notes.setFont(font)
        self.txt_notes.setObjectName("txt_notes")
        self.btn_Update_Maintenance_Info = QtWidgets.QPushButton(self.tab_3)
        self.btn_Update_Maintenance_Info.setGeometry(QtCore.QRect(120, 330, 121, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_Update_Maintenance_Info.setFont(font)
        self.btn_Update_Maintenance_Info.setObjectName("btn_Update_Maintenance_Info")
        self.btn_Add_Maintenance_Info = QtWidgets.QPushButton(self.tab_3)
        self.btn_Add_Maintenance_Info.setGeometry(QtCore.QRect(460, 330, 121, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_Add_Maintenance_Info.setFont(font)
        self.btn_Add_Maintenance_Info.setObjectName("btn_Add_Maintenance_Info")
        self.line_2 = QtWidgets.QFrame(self.tab_3)
        self.line_2.setGeometry(QtCore.QRect(351, 45, 20, 261))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.txt_infraction_info = QtWidgets.QLineEdit(self.tab_4)
        self.txt_infraction_info.setGeometry(QtCore.QRect(370, 210, 251, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt_infraction_info.setFont(font)
        self.txt_infraction_info.setObjectName("txt_infraction_info")
        self.txt_annual_infraction = QtWidgets.QLineEdit(self.tab_4)
        self.txt_annual_infraction.setGeometry(QtCore.QRect(64, 92, 251, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt_annual_infraction.setFont(font)
        self.txt_annual_infraction.setObjectName("txt_annual_infraction")
        self.txt_newcar_licence = QtWidgets.QLineEdit(self.tab_4)
        self.txt_newcar_licence.setGeometry(QtCore.QRect(370, 129, 251, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt_newcar_licence.setFont(font)
        self.txt_newcar_licence.setObjectName("txt_newcar_licence")
        self.txt_withdrawn_licence = QtWidgets.QLineEdit(self.tab_4)
        self.txt_withdrawn_licence.setGeometry(QtCore.QRect(63, 171, 251, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt_withdrawn_licence.setFont(font)
        self.txt_withdrawn_licence.setObjectName("txt_withdrawn_licence")
        self.txt_withdrawn_infraction = QtWidgets.QLineEdit(self.tab_4)
        self.txt_withdrawn_infraction.setGeometry(QtCore.QRect(62, 211, 251, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt_withdrawn_infraction.setFont(font)
        self.txt_withdrawn_infraction.setObjectName("txt_withdrawn_infraction")
        self.txt_stamping_receipts = QtWidgets.QLineEdit(self.tab_4)
        self.txt_stamping_receipts.setGeometry(QtCore.QRect(62, 131, 251, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt_stamping_receipts.setFont(font)
        self.txt_stamping_receipts.setObjectName("txt_stamping_receipts")
        self.txt_renew_permission = QtWidgets.QLineEdit(self.tab_4)
        self.txt_renew_permission.setGeometry(QtCore.QRect(370, 169, 251, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt_renew_permission.setFont(font)
        self.txt_renew_permission.setObjectName("txt_renew_permission")
        self.txt_annual_renew = QtWidgets.QLineEdit(self.tab_4)
        self.txt_annual_renew.setGeometry(QtCore.QRect(372, 89, 251, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt_annual_renew.setFont(font)
        self.txt_annual_renew.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.txt_annual_renew.setObjectName("txt_annual_renew")
        self.btn_Update_Licence_Info = QtWidgets.QPushButton(self.tab_4)
        self.btn_Update_Licence_Info.setGeometry(QtCore.QRect(110, 290, 121, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_Update_Licence_Info.setFont(font)
        self.btn_Update_Licence_Info.setObjectName("btn_Update_Licence_Info")
        self.btn_Add_Licence_Info = QtWidgets.QPushButton(self.tab_4)
        self.btn_Add_Licence_Info.setGeometry(QtCore.QRect(430, 290, 121, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_Add_Licence_Info.setFont(font)
        self.btn_Add_Licence_Info.setObjectName("btn_Add_Licence_Info")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.btn_Add_Revenu_Info = QtWidgets.QPushButton(self.tab_5)
        self.btn_Add_Revenu_Info.setGeometry(QtCore.QRect(350, 260, 121, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_Add_Revenu_Info.setFont(font)
        self.btn_Add_Revenu_Info.setObjectName("btn_Add_Revenu_Info")
        self.btn_Update_Revenu_Info = QtWidgets.QPushButton(self.tab_5)
        self.btn_Update_Revenu_Info.setGeometry(QtCore.QRect(220, 260, 121, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_Update_Revenu_Info.setFont(font)
        self.btn_Update_Revenu_Info.setObjectName("btn_Update_Revenu_Info")
        self.txt_kohna_selling = QtWidgets.QLineEdit(self.tab_5)
        self.txt_kohna_selling.setGeometry(QtCore.QRect(222, 90, 251, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt_kohna_selling.setFont(font)
        self.txt_kohna_selling.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.txt_kohna_selling.setObjectName("txt_kohna_selling")
        self.txt_accedint_compensation = QtWidgets.QLineEdit(self.tab_5)
        self.txt_accedint_compensation.setGeometry(QtCore.QRect(220, 170, 251, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt_accedint_compensation.setFont(font)
        self.txt_accedint_compensation.setObjectName("txt_accedint_compensation")
        self.txt_insurance_compensation = QtWidgets.QLineEdit(self.tab_5)
        self.txt_insurance_compensation.setGeometry(QtCore.QRect(220, 130, 251, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt_insurance_compensation.setFont(font)
        self.txt_insurance_compensation.setObjectName("txt_insurance_compensation")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.btn_Add_Rent_Info = QtWidgets.QPushButton(self.tab_6)
        self.btn_Add_Rent_Info.setGeometry(QtCore.QRect(336, 221, 121, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_Add_Rent_Info.setFont(font)
        self.btn_Add_Rent_Info.setObjectName("btn_Add_Rent_Info")
        self.txt_monthly_revenu = QtWidgets.QLineEdit(self.tab_6)
        self.txt_monthly_revenu.setGeometry(QtCore.QRect(208, 122, 251, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt_monthly_revenu.setFont(font)
        self.txt_monthly_revenu.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.txt_monthly_revenu.setObjectName("txt_monthly_revenu")
        self.txt_arab_ghofra = QtWidgets.QLineEdit(self.tab_6)
        self.txt_arab_ghofra.setGeometry(QtCore.QRect(207, 162, 251, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt_arab_ghofra.setFont(font)
        self.txt_arab_ghofra.setObjectName("txt_arab_ghofra")
        self.btn_Update_Rent_Info = QtWidgets.QPushButton(self.tab_6)
        self.btn_Update_Rent_Info.setGeometry(QtCore.QRect(206, 221, 121, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_Update_Rent_Info.setFont(font)
        self.btn_Update_Rent_Info.setObjectName("btn_Update_Rent_Info")
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.txt_electricity_expenses = QtWidgets.QLineEdit(self.tab_7)
        self.txt_electricity_expenses.setGeometry(QtCore.QRect(201, 110, 251, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt_electricity_expenses.setFont(font)
        self.txt_electricity_expenses.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.txt_electricity_expenses.setObjectName("txt_electricity_expenses")
        self.btn_Update_ElectricityWater_Info = QtWidgets.QPushButton(self.tab_7)
        self.btn_Update_ElectricityWater_Info.setGeometry(QtCore.QRect(199, 209, 121, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_Update_ElectricityWater_Info.setFont(font)
        self.btn_Update_ElectricityWater_Info.setObjectName("btn_Update_ElectricityWater_Info")
        self.btn_Add_ElectricityWater_Info = QtWidgets.QPushButton(self.tab_7)
        self.btn_Add_ElectricityWater_Info.setGeometry(QtCore.QRect(329, 209, 121, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_Add_ElectricityWater_Info.setFont(font)
        self.btn_Add_ElectricityWater_Info.setObjectName("btn_Add_ElectricityWater_Info")
        self.txt_water_expenses = QtWidgets.QLineEdit(self.tab_7)
        self.txt_water_expenses.setGeometry(QtCore.QRect(200, 150, 251, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt_water_expenses.setFont(font)
        self.txt_water_expenses.setObjectName("txt_water_expenses")
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_9)
        self.tabWidget_2.setGeometry(QtCore.QRect(20, 0, 661, 401))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget_2.setFont(font)
        self.tabWidget_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.tabWidget_2.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.pushButton_17 = QtWidgets.QPushButton(self.tab_10)
        self.pushButton_17.setGeometry(QtCore.QRect(503, 369, 121, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_17.setFont(font)
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(self.tab_10)
        self.pushButton_18.setGeometry(QtCore.QRect(373, 369, 121, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_18.setFont(font)
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(self.tab_10)
        self.pushButton_19.setGeometry(QtCore.QRect(113, 369, 121, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_19.setFont(font)
        self.pushButton_19.setObjectName("pushButton_19")
        self.groupBox = QtWidgets.QGroupBox(self.tab_10)
        self.groupBox.setGeometry(QtCore.QRect(0, 30, 651, 331))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox)
        self.tableWidget.setGeometry(QtCore.QRect(0, 20, 651, 311))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(12)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        self.radioButton = QtWidgets.QRadioButton(self.tab_10)
        self.radioButton.setGeometry(QtCore.QRect(470, 10, 131, 22))
        self.radioButton.setStyleSheet("QRadioButton {\n"
"    background-color : gray;\n"
"    color : white\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width : 10px;\n"
"    height : 10px;\n"
"    border-radius : 7px;   \n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color : black;\n"
"    border: 2px solid white;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color : white;\n"
"    border: 2px solid white;\n"
"}\n"
"")
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.tab_10)
        self.radioButton_2.setGeometry(QtCore.QRect(300, 10, 151, 22))
        self.radioButton_2.setStyleSheet("QRadioButton {\n"
"    background-color : gray;\n"
"    color : white\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width : 10px;\n"
"    height : 10px;\n"
"    border-radius : 7px;   \n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color : black;\n"
"    border: 2px solid white;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color : white;\n"
"    border: 2px solid white;\n"
"}\n"
"")
        self.radioButton_2.setObjectName("radioButton_2")
        self.pushButton = QtWidgets.QPushButton(self.tab_10)
        self.pushButton.setGeometry(QtCore.QRect(140, 10, 88, 29))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_10)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 10, 88, 29))
        self.pushButton_2.setObjectName("pushButton_2")
        self.tabWidget_2.addTab(self.tab_10, "")
        self.tab_15 = QtWidgets.QWidget()
        self.tab_15.setObjectName("tab_15")
        self.pushButton_11 = QtWidgets.QPushButton(self.tab_15)
        self.pushButton_11.setGeometry(QtCore.QRect(160, 10, 88, 29))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.tab_15)
        self.pushButton_12.setGeometry(QtCore.QRect(40, 10, 88, 29))
        self.pushButton_12.setObjectName("pushButton_12")
        self.radioButton_11 = QtWidgets.QRadioButton(self.tab_15)
        self.radioButton_11.setGeometry(QtCore.QRect(320, 10, 151, 22))
        self.radioButton_11.setStyleSheet("QRadioButton {\n"
"    background-color : gray;\n"
"    color : white\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width : 10px;\n"
"    height : 10px;\n"
"    border-radius : 7px;   \n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color : black;\n"
"    border: 2px solid white;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color : white;\n"
"    border: 2px solid white;\n"
"}\n"
"")
        self.radioButton_11.setObjectName("radioButton_11")
        self.radioButton_12 = QtWidgets.QRadioButton(self.tab_15)
        self.radioButton_12.setGeometry(QtCore.QRect(490, 10, 131, 22))
        self.radioButton_12.setStyleSheet("QRadioButton {\n"
"    background-color : gray;\n"
"    color : white\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width : 10px;\n"
"    height : 10px;\n"
"    border-radius : 7px;   \n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color : black;\n"
"    border: 2px solid white;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color : white;\n"
"    border: 2px solid white;\n"
"}\n"
"")
        self.radioButton_12.setObjectName("radioButton_12")
        self.tabWidget_2.addTab(self.tab_15, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_11)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 40, 661, 311))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.groupBox_2)
        self.tableWidget_2.setGeometry(QtCore.QRect(0, 20, 651, 311))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(12)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(11, item)
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_11)
        self.pushButton_3.setGeometry(QtCore.QRect(140, 10, 88, 29))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_11)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 10, 88, 29))
        self.pushButton_4.setObjectName("pushButton_4")
        self.radioButton_3 = QtWidgets.QRadioButton(self.tab_11)
        self.radioButton_3.setGeometry(QtCore.QRect(300, 10, 151, 22))
        self.radioButton_3.setStyleSheet("QRadioButton {\n"
"    background-color : gray;\n"
"    color : white\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width : 10px;\n"
"    height : 10px;\n"
"    border-radius : 7px;   \n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color : black;\n"
"    border: 2px solid white;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color : white;\n"
"    border: 2px solid white;\n"
"}\n"
"")
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.tab_11)
        self.radioButton_4.setGeometry(QtCore.QRect(470, 10, 131, 22))
        self.radioButton_4.setStyleSheet("QRadioButton {\n"
"    background-color : gray;\n"
"    color : white\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width : 10px;\n"
"    height : 10px;\n"
"    border-radius : 7px;   \n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color : black;\n"
"    border: 2px solid white;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color : white;\n"
"    border: 2px solid white;\n"
"}\n"
"\n"
"")
        self.radioButton_4.setObjectName("radioButton_4")
        self.tabWidget_2.addTab(self.tab_11, "")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_12)
        self.pushButton_5.setGeometry(QtCore.QRect(160, 10, 88, 29))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_12)
        self.pushButton_6.setGeometry(QtCore.QRect(40, 10, 88, 29))
        self.pushButton_6.setObjectName("pushButton_6")
        self.radioButton_5 = QtWidgets.QRadioButton(self.tab_12)
        self.radioButton_5.setGeometry(QtCore.QRect(320, 10, 151, 22))
        self.radioButton_5.setStyleSheet("QRadioButton {\n"
"    background-color : gray;\n"
"    color : white\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width : 10px;\n"
"    height : 10px;\n"
"    border-radius : 7px;   \n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color : black;\n"
"    border: 2px solid white;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color : white;\n"
"    border: 2px solid white;\n"
"}\n"
"")
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_6 = QtWidgets.QRadioButton(self.tab_12)
        self.radioButton_6.setGeometry(QtCore.QRect(490, 10, 131, 22))
        self.radioButton_6.setStyleSheet("QRadioButton {\n"
"    background-color : gray;\n"
"    color : white\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width : 10px;\n"
"    height : 10px;\n"
"    border-radius : 7px;   \n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color : black;\n"
"    border: 2px solid white;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color : white;\n"
"    border: 2px solid white;\n"
"}\n"
"")
        self.radioButton_6.setObjectName("radioButton_6")
        self.tabWidget_2.addTab(self.tab_12, "")
        self.tab_13 = QtWidgets.QWidget()
        self.tab_13.setObjectName("tab_13")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_13)
        self.pushButton_7.setGeometry(QtCore.QRect(150, 10, 88, 29))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_13)
        self.pushButton_8.setGeometry(QtCore.QRect(30, 10, 88, 29))
        self.pushButton_8.setObjectName("pushButton_8")
        self.radioButton_7 = QtWidgets.QRadioButton(self.tab_13)
        self.radioButton_7.setGeometry(QtCore.QRect(310, 10, 151, 22))
        self.radioButton_7.setStyleSheet("QRadioButton {\n"
"    background-color : gray;\n"
"    color : white\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width : 10px;\n"
"    height : 10px;\n"
"    border-radius : 7px;   \n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color : black;\n"
"    border: 2px solid white;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color : white;\n"
"    border: 2px solid white;\n"
"}\n"
"")
        self.radioButton_7.setObjectName("radioButton_7")
        self.radioButton_8 = QtWidgets.QRadioButton(self.tab_13)
        self.radioButton_8.setGeometry(QtCore.QRect(480, 10, 131, 22))
        self.radioButton_8.setStyleSheet("QRadioButton {\n"
"    background-color : gray;\n"
"    color : white\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width : 10px;\n"
"    height : 10px;\n"
"    border-radius : 7px;   \n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color : black;\n"
"    border: 2px solid white;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color : white;\n"
"    border: 2px solid white;\n"
"}\n"
"")
        self.radioButton_8.setObjectName("radioButton_8")
        self.tabWidget_2.addTab(self.tab_13, "")
        self.tab_14 = QtWidgets.QWidget()
        self.tab_14.setObjectName("tab_14")
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_14)
        self.pushButton_9.setGeometry(QtCore.QRect(160, 10, 88, 29))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_14)
        self.pushButton_10.setGeometry(QtCore.QRect(40, 10, 88, 29))
        self.pushButton_10.setObjectName("pushButton_10")
        self.radioButton_9 = QtWidgets.QRadioButton(self.tab_14)
        self.radioButton_9.setGeometry(QtCore.QRect(320, 10, 151, 22))
        self.radioButton_9.setStyleSheet("QRadioButton {\n"
"    background-color : gray;\n"
"    color : white\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width : 10px;\n"
"    height : 10px;\n"
"    border-radius : 7px;   \n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color : black;\n"
"    border: 2px solid white;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color : white;\n"
"    border: 2px solid white;\n"
"}\n"
"")
        self.radioButton_9.setObjectName("radioButton_9")
        self.radioButton_10 = QtWidgets.QRadioButton(self.tab_14)
        self.radioButton_10.setGeometry(QtCore.QRect(490, 10, 131, 22))
        self.radioButton_10.setStyleSheet("QRadioButton {\n"
"    background-color : gray;\n"
"    color : white\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width : 10px;\n"
"    height : 10px;\n"
"    border-radius : 7px;   \n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color : black;\n"
"    border: 2px solid white;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color : white;\n"
"    border: 2px solid white;\n"
"}\n"
"")
        self.radioButton_10.setObjectName("radioButton_10")
        self.tabWidget_2.addTab(self.tab_14, "")
        self.tab_16 = QtWidgets.QWidget()
        self.tab_16.setObjectName("tab_16")
        self.pushButton_13 = QtWidgets.QPushButton(self.tab_16)
        self.pushButton_13.setGeometry(QtCore.QRect(150, 10, 88, 29))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.tab_16)
        self.pushButton_14.setGeometry(QtCore.QRect(30, 10, 88, 29))
        self.pushButton_14.setObjectName("pushButton_14")
        self.radioButton_13 = QtWidgets.QRadioButton(self.tab_16)
        self.radioButton_13.setGeometry(QtCore.QRect(310, 10, 151, 22))
        self.radioButton_13.setStyleSheet("QRadioButton {\n"
"    background-color : gray;\n"
"    color : white\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width : 10px;\n"
"    height : 10px;\n"
"    border-radius : 7px;   \n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color : black;\n"
"    border: 2px solid white;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color : white;\n"
"    border: 2px solid white;\n"
"}\n"
"")
        self.radioButton_13.setObjectName("radioButton_13")
        self.radioButton_14 = QtWidgets.QRadioButton(self.tab_16)
        self.radioButton_14.setGeometry(QtCore.QRect(480, 10, 131, 22))
        self.radioButton_14.setStyleSheet("QRadioButton {\n"
"    background-color : gray;\n"
"    color : white\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width : 10px;\n"
"    height : 10px;\n"
"    border-radius : 7px;   \n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color : black;\n"
"    border: 2px solid white;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color : white;\n"
"    border: 2px solid white;\n"
"}\n"
"")
        self.radioButton_14.setObjectName("radioButton_14")
        self.tabWidget_2.addTab(self.tab_16, "")
        self.tabWidget.addTab(self.tab_9, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_8)
        self.groupBox_3.setGeometry(QtCore.QRect(340, 0, 331, 401))
        self.groupBox_3.setObjectName("groupBox_3")
        self.btn_Add_User = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_Add_User.setGeometry(QtCore.QRect(40, 289, 241, 41))
        self.btn_Add_User.setObjectName("btn_Add_User")
        self.txt_User_Name = QtWidgets.QLineEdit(self.groupBox_3)
        self.txt_User_Name.setGeometry(QtCore.QRect(40, 95, 241, 41))
        self.txt_User_Name.setObjectName("txt_User_Name")
        self.txt_Password1 = QtWidgets.QLineEdit(self.groupBox_3)
        self.txt_Password1.setGeometry(QtCore.QRect(40, 152, 241, 41))
        self.txt_Password1.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_Password1.setObjectName("txt_Password1")
        self.txt_Password2 = QtWidgets.QLineEdit(self.groupBox_3)
        self.txt_Password2.setGeometry(QtCore.QRect(40, 209, 241, 41))
        self.txt_Password2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_Password2.setObjectName("txt_Password2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_8)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 0, 331, 401))
        self.groupBox_4.setObjectName("groupBox_4")
        self.btn_Update_User_Password = QtWidgets.QPushButton(self.groupBox_4)
        self.btn_Update_User_Password.setGeometry(QtCore.QRect(40, 290, 241, 41))
        self.btn_Update_User_Password.setObjectName("btn_Update_User_Password")
        self.txt_Old_Password = QtWidgets.QLineEdit(self.groupBox_4)
        self.txt_Old_Password.setGeometry(QtCore.QRect(40, 121, 241, 41))
        self.txt_Old_Password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_Old_Password.setObjectName("txt_Old_Password")
        self.txt_New_Password1 = QtWidgets.QLineEdit(self.groupBox_4)
        self.txt_New_Password1.setGeometry(QtCore.QRect(40, 174, 241, 41))
        self.txt_New_Password1.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_New_Password1.setObjectName("txt_New_Password1")
        self.txt_User_Name1 = QtWidgets.QLineEdit(self.groupBox_4)
        self.txt_User_Name1.setGeometry(QtCore.QRect(40, 69, 241, 41))
        self.txt_User_Name1.setObjectName("txt_User_Name1")
        self.txt_New_Password2 = QtWidgets.QLineEdit(self.groupBox_4)
        self.txt_New_Password2.setGeometry(QtCore.QRect(40, 227, 241, 41))
        self.txt_New_Password2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_New_Password2.setObjectName("txt_New_Password2")
        self.tabWidget.addTab(self.tab_8, "")
        self.txt_Search_For_CarData_By_CarNo = QtWidgets.QLineEdit(Dialog)
        self.txt_Search_For_CarData_By_CarNo.setGeometry(QtCore.QRect(170, 40, 451, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt_Search_For_CarData_By_CarNo.setFont(font)
        self.txt_Search_For_CarData_By_CarNo.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.txt_Search_For_CarData_By_CarNo.setObjectName("txt_Search_For_CarData_By_CarNo")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btn_Search_For_CarData_By_CarNo.setText(_translate("Dialog", "بحث"))
        self.txt_Car_Car_Number.setPlaceholderText(_translate("Dialog", "رقم العربية"))
        self.txt_Car_Shaceh_Number.setPlaceholderText(_translate("Dialog", "رقم الشاسيه"))
        self.txt_Car_Motor_Number.setPlaceholderText(_translate("Dialog", "رقم الموتور"))
        self.txt_Car_Owner_Company.setPlaceholderText(_translate("Dialog", "الشركة المالكة"))
        self.txt_Car_Branch.setPlaceholderText(_translate("Dialog", "الفرع"))
        self.txt_Car_Car_Load.setPlaceholderText(_translate("Dialog", "حمولة العربية"))
        self.txt_Car_Car_Wieght.setPlaceholderText(_translate("Dialog", "الوزن"))
        self.txt_Car_Car_Shape.setPlaceholderText(_translate("Dialog", "الشكل"))
        self.txt_Car_Car_Type.setPlaceholderText(_translate("Dialog", "نوع العربية"))
        self.txt_Car_Car_Model.setPlaceholderText(_translate("Dialog", "موديل العربية"))
        self.txt_Car_Car_Color.setPlaceholderText(_translate("Dialog", "اللون"))
        self.btn_Add_Car_Info.setText(_translate("Dialog", "إضافة معلومات"))
        self.btn_Update_Car_Info.setText(_translate("Dialog", "تعديل معلومات"))
        self.btn_Delete_Car_Info.setText(_translate("Dialog", "مسح المعلومات"))
        self.cbo_Car_Service_Mode.setToolTip(_translate("Dialog", "نوع الخدمة"))
        self.cbo_Car_Service_Mode.setItemText(0, _translate("Dialog", "بيع"))
        self.cbo_Car_Service_Mode.setItemText(1, _translate("Dialog", "ملاكي"))
        self.cbo_Car_Service_Mode.setItemText(2, _translate("Dialog", "خدمة مصنع"))
        self.cbo_Car_Fuel_Type.setToolTip(_translate("Dialog", "نوع الوقود"))
        self.cbo_Car_Fuel_Type.setItemText(0, _translate("Dialog", "بنزين"))
        self.cbo_Car_Fuel_Type.setItemText(1, _translate("Dialog", "سولار"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "العربيات"))
        self.liter_number.setPlaceholderText(_translate("Dialog", "عدد الليترات"))
        self.liter_price.setPlaceholderText(_translate("Dialog", "سعر الليتر"))
        self.tips.setPlaceholderText(_translate("Dialog", "الإكراميات"))
        self.meter_reading.setPlaceholderText(_translate("Dialog", "قراءة العداد"))
        self.label.setText(_translate("Dialog", "الإجمالي"))
        self.btn_Update_Fuel_Info.setText(_translate("Dialog", "تعديل معلومات"))
        self.btn_Add_Fuel_Info.setText(_translate("Dialog", "إضافة معلومات"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "الوقود"))
        self.txt_afsha.setPlaceholderText(_translate("Dialog", "العفشة"))
        self.txt_engine_amra.setPlaceholderText(_translate("Dialog", "عمرة المحركات"))
        self.txt_periodic_maintenance.setPlaceholderText(_translate("Dialog", "الصيانة الدورية"))
        self.txt_samkara.setPlaceholderText(_translate("Dialog", "السمكرة"))
        self.txt_electricity.setPlaceholderText(_translate("Dialog", "الكهرباء"))
        self.txt_cooling.setPlaceholderText(_translate("Dialog", "التبريد"))
        self.txt_mechanics.setPlaceholderText(_translate("Dialog", "الميكانيكا"))
        self.txt_glass.setPlaceholderText(_translate("Dialog", "الزجاج"))
        self.txt_notes.setPlainText(_translate("Dialog", "الملاحظات"))
        self.btn_Update_Maintenance_Info.setText(_translate("Dialog", "تعديل معلومات"))
        self.btn_Add_Maintenance_Info.setText(_translate("Dialog", "إضافة معلومات"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "الصيانة"))
        self.txt_infraction_info.setPlaceholderText(_translate("Dialog", "المخالفات"))
        self.txt_annual_infraction.setPlaceholderText(_translate("Dialog", "المخالفات السنوية"))
        self.txt_newcar_licence.setPlaceholderText(_translate("Dialog", "رخصة سيارة جديدة"))
        self.txt_withdrawn_licence.setPlaceholderText(_translate("Dialog", "غرامة رخصة"))
        self.txt_withdrawn_infraction.setPlaceholderText(_translate("Dialog", "غرامة مخالفات"))
        self.txt_stamping_receipts.setPlaceholderText(_translate("Dialog", "الإيصالات"))
        self.txt_renew_permission.setPlaceholderText(_translate("Dialog", "تصريح التجديد"))
        self.txt_annual_renew.setPlaceholderText(_translate("Dialog", "التجديد السنوي"))
        self.btn_Update_Licence_Info.setText(_translate("Dialog", "تعديل معلومات"))
        self.btn_Add_Licence_Info.setText(_translate("Dialog", "إضافة معلومات"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Dialog", "التراخيص"))
        self.btn_Add_Revenu_Info.setText(_translate("Dialog", "إضافة معلومات"))
        self.btn_Update_Revenu_Info.setText(_translate("Dialog", "تعديل معلومات"))
        self.txt_kohna_selling.setPlaceholderText(_translate("Dialog", "بيع الكهنة"))
        self.txt_accedint_compensation.setPlaceholderText(_translate("Dialog", "تعويضات الحوادث"))
        self.txt_insurance_compensation.setPlaceholderText(_translate("Dialog", "تعويضات التأمين"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Dialog", "الإيرادات"))
        self.btn_Add_Rent_Info.setText(_translate("Dialog", "إضافة معلومات"))
        self.txt_monthly_revenu.setPlaceholderText(_translate("Dialog", "العائد الشهري"))
        self.txt_arab_ghofra.setPlaceholderText(_translate("Dialog", "عرب غفرة"))
        self.btn_Update_Rent_Info.setText(_translate("Dialog", "تعديل معلومات"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("Dialog", "الإيجارات"))
        self.txt_electricity_expenses.setPlaceholderText(_translate("Dialog", "مصروفات الكهرباء"))
        self.btn_Update_ElectricityWater_Info.setText(_translate("Dialog", "تعديل معلومات"))
        self.btn_Add_ElectricityWater_Info.setText(_translate("Dialog", "إضافة معلومات"))
        self.txt_water_expenses.setPlaceholderText(_translate("Dialog", "مصروفات المياة"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("Dialog", "الكهرباء"))
        self.pushButton_17.setText(_translate("Dialog", "إضافة معلومات"))
        self.pushButton_18.setText(_translate("Dialog", "تعديل معلومات"))
        self.pushButton_19.setText(_translate("Dialog", "مسح المعلومات"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "رقم  السيارة"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "الشركة المالكة"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "الفرع"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "نوع الخدمة"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "رقم الشاسيه"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "رقم الموتور"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "نوع السيارة"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Dialog", "موديل السيارة"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("Dialog", "موديل العربية"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("Dialog", "حموله"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("Dialog", "وزن"))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("Dialog", "لون السيارة"))
        self.radioButton.setText(_translate("Dialog", "سيارة واحدة"))
        self.radioButton_2.setText(_translate("Dialog", "كل السيارات"))
        self.pushButton.setText(_translate("Dialog", "عرض النتيجه"))
        self.pushButton_2.setText(_translate("Dialog", "طباعة التقرير"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_10), _translate("Dialog", "العربيات"))
        self.pushButton_11.setText(_translate("Dialog", "عرض النتيجه"))
        self.pushButton_12.setText(_translate("Dialog", "طباعة التقرير"))
        self.radioButton_11.setText(_translate("Dialog", "كل السيارات"))
        self.radioButton_12.setText(_translate("Dialog", "سيارة واحدة"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_15), _translate("Dialog", "الإيجارات"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "رقم  السيارة"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "الشركة المالكة"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "الفرع"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "نوع الخدمة"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "رقم الشاسيه"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "رقم الموتور"))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "نوع السيارة"))
        item = self.tableWidget_2.horizontalHeaderItem(7)
        item.setText(_translate("Dialog", "موديل السيارة"))
        item = self.tableWidget_2.horizontalHeaderItem(8)
        item.setText(_translate("Dialog", "موديل العربية"))
        item = self.tableWidget_2.horizontalHeaderItem(9)
        item.setText(_translate("Dialog", "حموله"))
        item = self.tableWidget_2.horizontalHeaderItem(10)
        item.setText(_translate("Dialog", "وزن"))
        item = self.tableWidget_2.horizontalHeaderItem(11)
        item.setText(_translate("Dialog", "لون السيارة"))
        self.pushButton_3.setText(_translate("Dialog", "عرض النتيجه"))
        self.pushButton_4.setText(_translate("Dialog", "طباعة التقرير"))
        self.radioButton_3.setText(_translate("Dialog", "كل السيارات"))
        self.radioButton_4.setText(_translate("Dialog", "سيارة واحدة"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_11), _translate("Dialog", "الوقود"))
        self.pushButton_5.setText(_translate("Dialog", "عرض النتيجه"))
        self.pushButton_6.setText(_translate("Dialog", "طباعة التقرير"))
        self.radioButton_5.setText(_translate("Dialog", "كل السيارات"))
        self.radioButton_6.setText(_translate("Dialog", "سيارة واحدة"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_12), _translate("Dialog", "الصيانة"))
        self.pushButton_7.setText(_translate("Dialog", "عرض النتيجه"))
        self.pushButton_8.setText(_translate("Dialog", "طباعة التقرير"))
        self.radioButton_7.setText(_translate("Dialog", "كل السيارات"))
        self.radioButton_8.setText(_translate("Dialog", "سيارة واحدة"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_13), _translate("Dialog", "التراخيص"))
        self.pushButton_9.setText(_translate("Dialog", "عرض النتيجه"))
        self.pushButton_10.setText(_translate("Dialog", "طباعة التقرير"))
        self.radioButton_9.setText(_translate("Dialog", "كل السيارات"))
        self.radioButton_10.setText(_translate("Dialog", "سيارة واحدة"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_14), _translate("Dialog", "الإيرادات"))
        self.pushButton_13.setText(_translate("Dialog", "عرض النتيجه"))
        self.pushButton_14.setText(_translate("Dialog", "طباعة التقرير"))
        self.radioButton_13.setText(_translate("Dialog", "كل السيارات"))
        self.radioButton_14.setText(_translate("Dialog", "سيارة واحدة"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_16), _translate("Dialog", "الكهرباء"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), _translate("Dialog", "التقارير"))
        self.groupBox_3.setTitle(_translate("Dialog", "اضافة مستخدم جديد"))
        self.btn_Add_User.setText(_translate("Dialog", "إضافة معلومات المستخدم"))
        self.txt_User_Name.setPlaceholderText(_translate("Dialog", "إدخل اسم المستخدم"))
        self.txt_Password1.setPlaceholderText(_translate("Dialog", "إدخل كلمة المرور"))
        self.txt_Password2.setPlaceholderText(_translate("Dialog", "إدخل كلمة المرور مرة أخري"))
        self.groupBox_4.setTitle(_translate("Dialog", "تعديل معلومات مستخدم"))
        self.btn_Update_User_Password.setText(_translate("Dialog", "تعديل معلومات المستخدم"))
        self.txt_Old_Password.setPlaceholderText(_translate("Dialog", "إدخل كلمة المرور القديمة"))
        self.txt_New_Password1.setPlaceholderText(_translate("Dialog", "إدخل كلمة المرور الجديدة"))
        self.txt_User_Name1.setPlaceholderText(_translate("Dialog", "إدخل اسم المستخدم"))
        self.txt_New_Password2.setPlaceholderText(_translate("Dialog", "إدخل كلمة المرور الجديدة مرة أخري"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("Dialog", "المستخدمين"))
        self.txt_Search_For_CarData_By_CarNo.setPlaceholderText(_translate("Dialog", "إدخل رقم العربية"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
